
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Complete(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

wire clock_1hz;


//=======================================================
//  REG/WIRE declarations
//=======================================================


//butts


//=======================================================
//  Structural coding
//=======================================================
assign LED[0] = SW[0]; 

clock_divider #(5_000_000) u0 (.clk(ADC_CLK_10),.reset_n(KEY[0]),.outclk(clock_1Hz)); 


endmodule
